Vidly/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public Genre Genre { get; set; }

        [Display(Name = "Genre")]
        [Required]
        public byte GenreId { get; set; }

        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }
        
        public DateTime DateAdded { get; set; }

        [Display(Name = "Number in Stock")]
        [Range(1, 20)]
        public int NumberInStock { get; set; }
    } 
}

Vidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext _dbContext;

        public MoviesController()
        {
            _dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _dbContext.Dispose();
        }

        public ActionResult Index()
        {
            var movieList = _dbContext.Movies.Include(c => c.Genre).ToList();

            return View(movieList);
        }

        public ActionResult New_Movie()
        {
            var genreList = _dbContext.Genres.ToList();

            var movieViewModel = new MovieFormViewModel()
            {
                Genre = genreList
            };

            return View("MovieForm", movieViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save_Movie(Movie movie)
         {
            if(!ModelState.IsValid)
            {
                var viewModel = new MovieFormViewModel(movie)
                {
                    Genre = _dbContext.Genres.ToList()
                };
                return View("MovieForm", viewModel);
            }

            if(movie.Id == 0)
            {
                movie.DateAdded = DateTime.Now.Date;
                _dbContext.Movies.Add(movie);
            }
            else
            {
                var movieInDb = _dbContext.Movies.Single(m => m.Id == movie.Id);

                movieInDb.Name = movie.Name;
                movieInDb.ReleaseDate = movie.ReleaseDate;
                movieInDb.GenreId = movie.GenreId;
                movieInDb.NumberInStock = movie.NumberInStock;
            }

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit_Movie(int id)
        {
            var movie = _dbContext.Movies.SingleOrDefault(m => m.Id == id);

            if(movie == null)
            {
                return HttpNotFound();
            }

            var movieViewModel = new MovieFormViewModel(movie)
            {
                Genre = _dbContext.Genres.ToList()
            };

            return View("MovieForm", movieViewModel);
        }

        public ActionResult Details(int id)
        {
            var movie = _dbContext.Movies.Include(x => x.Genre).SingleOrDefault(x => x.Id == id);

            return View(movie);
        }

        public ActionResult Random()
        {
            var movie = new Movie() { Name = "Shrek" };

            var customers = new List<Customer>
            {
                new Customer { Name = "Customer1" },
                new Customer { Name = "Customer2" }
            };

            var viewModels = new RandomMovieViewModel
            {
                Movie = movie,
                Customers = customers
            };

            return View(viewModels);
        }

        //public ActionResult Index(int? pageIndex, string sortBy)
        //{
        //    var movie = new Movie() { Name = "Index" };

        //    if(!pageIndex.HasValue)
        //    {
        //        pageIndex = 1;
        //    }
        //    if(string.IsNullOrWhiteSpace(sortBy))
        //    {
        //        sortBy = "Name";
        //    }
        //    return Content(string.Format("Page Index = {0}, Sort By = {1}", pageIndex, sortBy));
        //}

        [Route("movies/released/{year}/{month:regex(\\d{2}):range(1,12)}")]
        public ActionResult ByReleaseDate(int year, int month)
        {

            return Content("Year =" + year + " && Month = " + month);
        }

        public ActionResult SampleAction(int id)
        {
            return Content(string.Format("{0}", id));
        }
    }
}

Vidly/Views/Movies/Details.cshtml
@model Vidly.Models.Movie
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

<ul>
    <li>Genre: @Model.Genre.Name</li>
    <li>Release Date: @Model.ReleaseDate.DayOfWeek, @Model.ReleaseDate.ToString("MMMM") @Model.ReleaseDate.Day, @Model.ReleaseDate.Year</li>
    <li>Date Added: @Model.DateAdded.DayOfWeek, @Model.DateAdded.ToString("MMMM") @Model.DateAdded.Day, @Model.DateAdded.Year</li>
    <li>Number in Stock: @Model.NumberInStock</li>
</ul>

Vidly/Views/Movies/Index.cshtml
@model IEnumerable<Vidly.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

<div class="form-group">
    @Html.ActionLink("New Movie", "New_Movie", "Movies", null, new { @class = "btn btn-primary" })
</div>

@if (!Model.Any())
{
    <text>No movies available yet.</text>
}
else
{
    <table class="table table-bordered table-hover table-dark">
        <thead>
            <tr>
                <th>Movie</th>
                <th>Genre</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr>
                    <td>@Html.ActionLink(movie.Name, "Edit_Movie", "Movies", new { id = movie.Id }, null)</td>
                    <td>@movie.Genre.Name</td>
                </tr>
            }
        </tbody>
    </table>
}

Vidly/Views/Movies/MovieForm.cshtml
@model Vidly.ViewModels.MovieFormViewModel
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Title</h2>

@using (Html.BeginForm("Save_Movie", "Movies"))
{
    @Html.ValidationSummary() //if excludePropertyError is true, it will not work because of the jquery val below
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ReleaseDate)
        @Html.TextBoxFor(m => m.ReleaseDate, "{0:MM/d/yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ReleaseDate)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.GenreId)
        @Html.DropDownListFor(m => m.GenreId, new SelectList(Model.Genre, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.GenreId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NumberInStock)
        @Html.TextBoxFor(m => m.NumberInStock, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.NumberInStock)
    </div>

    @Html.HiddenFor(m => m.Id)
    
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Vidly/Views/Movies/Random.cshtml
@model Vidly.ViewModels.RandomMovieViewModel
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ 
    var className = Model.Customers.Count > 1 ? "popular" : null;
}
<h2 class="@className">@Model.Movie.Name</h2>

@if(Model.Customers.Count == 0)
{
    <text>No one has rented this movie.</text>
}
else
{
    <ul>
        @foreach (var customer in Model.Customers)
        {
            <li>@customer.Name</li>
        }
    </ul>
}