Vidly/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Vidly.Models.Validation;

namespace Vidly.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public bool IsSubscribedToNewsLetter { get; set; }

        public MembershipType MembershipType { get; set; }

        [Display(Name = "Membership Type")]
        public byte MembershipTypeId { get; set; }
        
        [Display(Name = "Date of Birth")]
        [Min18YearsIfAMember]
        public DateTime? Birthdate { get; set; }
    }
}

Vidly/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext _dbContext;

        public CustomersController()
        {
            _dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _dbContext.Dispose();
        }

        // GET: Customers
        public ActionResult Index()
        {
            var customer = _dbContext.Customers.Include(c => c.MembershipType).ToList();

            return View(customer);
        }
        
        public ActionResult Details(int id)
        {
            var selectCustomer = _dbContext.Customers.Include(c => c.MembershipType).SingleOrDefault(x => x.Id == id);
            if(selectCustomer == null)
            {
                return HttpNotFound();
            }

            return View(selectCustomer);
        }

        public ActionResult New()
        {
            var membershipTypes = _dbContext.MembershipTypes.ToList();

            var customerViewModel = new CustomerFormViewModel()
            {
                Customers = new Customer(),
                MembershipTypes = membershipTypes
            };

            return View("CustomerForm", customerViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CustomerFormViewModel customer_model)
        {
            if(!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customers = customer_model.Customers,
                    MembershipTypes = _dbContext.MembershipTypes.ToList()
                };
                return View("CustomerForm", viewModel);
            }

            if(customer_model.Customers.Id == 0)
            {
                _dbContext.Customers.Add(customer_model.Customers);
            }
            else
            {
                var customerInDB = _dbContext.Customers.Single(c => c.Id == customer_model.Customers.Id);

                customerInDB.Name = customer_model.Customers.Name;
                customerInDB.Birthdate = customer_model.Customers.Birthdate;
                customerInDB.MembershipTypeId = customer_model.Customers.MembershipTypeId;
                customerInDB.IsSubscribedToNewsLetter = customer_model.Customers.IsSubscribedToNewsLetter;
            }
            
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var customer = _dbContext.Customers.SingleOrDefault(c => c.Id == id);

            if(customer == null)
            {
                return HttpNotFound();
            }

            var customerModel = new CustomerFormViewModel()
            {
                Customers = customer,
                MembershipTypes = _dbContext.MembershipTypes.ToList()
            };

            return View("CustomerForm", customerModel);
        }
    }
}

Vidly/Views/Customers/CustomerForm.cshtml
@model Vidly.ViewModels.CustomerFormViewModel
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Title</h2>

@using (Html.BeginForm("Save", "Customers"))
{
    @Html.ValidationSummary() //if excludePropertyError is true, it will not work because of the jquery val below
    <div class="form-group">
        @Html.LabelFor(m => m.Customers.Name)
        @Html.TextBoxFor(m => m.Customers.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customers.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Customers.MembershipTypeId)
        @Html.DropDownListFor(m => m.Customers.MembershipTypeId, new SelectList(Model.MembershipTypes, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customers.MembershipTypeId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Customers.Birthdate)
        @Html.TextBoxFor(m => m.Customers.Birthdate, "{0:d/MM/yyyy}", new { @class= "form-control" })
        @Html.ValidationMessageFor(m => m.Customers.Birthdate)
    </div>
    <div class="form-group">
        <label>
            @Html.CheckBoxFor(m => m.Customers.IsSubscribedToNewsLetter) Subscribed to Newsletter?
        </label>
    </div>
    @Html.HiddenFor(m => m.Customers.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-success">Save</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Vidly/Views/Customers/Details.cshtml
@model Vidly.Models.Customer
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

<ul>
    <li>Membership Type: @Model.MembershipType.Name</li>
    @if (Model.Birthdate.HasValue)
    {
        <li>Birthdate: @Model.Birthdate.Value.ToShortDateString()</li>
    }
</ul>

Vidly/Views/Customers/Index.cshtml
@model IEnumerable<Vidly.Models.Customer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>

<div class="form-group">
    @Html.ActionLink("New Customer", "New", "Customers", null, new { @class = "btn btn-primary" })
</div>

@if (!Model.Any())
{
    <text>We don't have any customers yet.</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Customer</th>
                <th>Membership Type</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@Html.ActionLink(@customer.Name, "Edit", "Customers", new { id = @customer.Id }, null)</td>
                    <td>@customer.MembershipType.Name</td>
                </tr>
            }
        </tbody>
    </table>
}